print("Please enter the follwing information so I can sell it for a profit!\n")
Fname=input("First name:")
Lname=input("Last name:")
grade=input("Grade (9-12):")
ID=input("Student ID:")
log=input("Login:")
gpa=input("GPA (0.0-4.0:)")
print("\n")
print("Your information")
print("\t Login: {}".format(log))
print("\t Student Id: {}".format(ID))
print("\t Name: {},{}".format(Fname,Lname))
print("\t GPA: {}".format(gpa))
print("\t Grade: {}".format(grade))